apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ocallaje/gitops.git
    path: apps/genelink-cluster
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true