apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd  # Argo CD's namespace
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-helm
    targetRevision: main
    path: charts/argo-workflows
    helm:
      values: |
        workflow:
          serviceAccount:
            create: true
            name: "argo-workflow"
          rbac:
            create: true
        controller:
          workflowNamespaces:
            - nextflow
        server:
          enabled: true
          serviceType: NodePort   
          serviceNodePort: 31500
          authModes: [server]        
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows      # workflows namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
