apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seqworks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ocallaje/GitOps.git
    path: deployments/dev-cluster/seqworks
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: seqworks
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

