apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-controller
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "secrets", "configmaps", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-controller
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo
roleRef:
  kind: Role
  name: argocd-app-controller
  apiGroup: rbac.authorization.k8s.io
