auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin132
##
## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
##
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    existingSecret: keycloak-postgresql
    secretKeys:
      userPasswordKey: postgres-password
    database: bitnami_keycloak
## Service configuration
##
service:
  ## Service type.
  ##
  type: ClusterIP
## Ingress configuration
##
ingress:
  enabled: false
  #hostname: keycloak.springadome.duckdns.org
  #ingressClassName: traefik
  #path: /
  #pathType: Prefix
  #servicePort: http

  #tls: true
  #selfSigned: false  # unless you're testing

  #annotations:
  #  kubernetes.io/ingress.class: traefik
  #  cert-manager.io/cluster-issuer: letsencrypt-prod  # or staging for test
