auth:
  adminUser: admin
  adminPassword: admin132
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: nztdql3mDa
    database: bitnami_keycloak
ingress:
  enabled: true
  hostname: keycloak.springadome.duckdns.org
  ingressClassName: traefik