apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ocallaje/GitOps.git
    path: namespaces/genelink-cluster
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      selfHeal: true
