argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    server:
  service:
    type: NodePort
    ports:
      - name: http
        port: 80
        nodePort: 30080
      - name: https
        port: 443
        nodePort: 30443
    extraArgs:
      - --insecure
  redisSecretInit:
    enabled: false