apiVersion: apps/v1
kind: Deployment
metadata:
  name: seqworks
  namespace: seqworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seqworks
  template:
    metadata:
      labels:
        app: seqworks
    spec:
      serviceAccountName: seqworks-argo-trigger
      containers:
      - name: seqworks
        image: alpine:latest
        command: ["sleep", "3600"]
        volumeMounts:
            - name: token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: argo-workflows