apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextflow-workdir
  namespace: nextflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Ti
