# Service account for Seqworks to access argo-workflows API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seqworks-argo-trigger
  namespace: seqworks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seqworks-trigger-role
  namespace: seqworks
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seqworks-trigger-rolebinding
  namespace: seqworks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seqworks-trigger-role
subjects:
- kind: ServiceAccount
  name: seqworks-argo-trigger


---
# service account that runs the nextflow workflow template
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow-submitter
  namespace: nextflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-submitter-role
  namespace: nextflow
rules:
  - apiGroups: ["argoproj.io", "batch"]
    resources: ["workflows", "workflowtemplates", "workflowtaskresults", "jobs"]
    verbs: ["get", "list", "create", "watch", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "persistentvolumeclaims", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-submitter-binding
  namespace: nextflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-submitter-role
subjects:
  - kind: ServiceAccount
    name: nextflow-submitter
    namespace: nextflow
