# apps/argo-trigger-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seqworks-argo-trigger
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seqworks-trigger-role
  namespace: argo-workflows
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seqworks-trigger-rolebinding
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seqworks-trigger-role
subjects:
- kind: ServiceAccount
  name: seqworks-argo-trigger
---  
apiVersion: v1
kind: Secret
metadata:
  name: seqworks-argo-trigger-token
  annotations:
    kubernetes.io/service-account.name: seqworks-argo-trigger
type: kubernetes.io/service-account-token
